# This file was automatically generated by sub/epyqlib/epyqlib/cli/generateversion.py
__version_build_time__ = '2024-04-16T22:55:23.450704'

__version__ = '0.0.0'
__sha__ = '6680080eaa85c0715fd49a77da83684bc0d67569'
__revision__ = '6680080eaa85c0715fd49a77da83684bc0d67569'
